### ISSUE TITLE
Implement WebDriver

### ISSUE THREAD

**Issue by munichbughunter** [p7s1-ctf/SevenFacette#60]
Implement a 7Facette driver. 
This should use the WebDriverManager (https://github.com/bonigarcia/webdrivermanager/)
for local testing. 
And also the Remote Web Driver for a Selenium Grid.

**Comment by PDoering** [comment]
I made a basic implementation of a 7Facette Driver called FDriver. 

The following features are there and already tested: 
* Local execution: Here we get a driver from the WebDriverManager. 
* Execution via Selenium Grid
* Standard Selenium Screenshotting
* Element interaction like click Link, click Button and write Text from the standard
* File upload via Selenium Grid is possible
* Screen comparison
* Snapshotting of a selected Element
* Snapshotting of the whole page, inclusive scroll up and down
